//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.19 at 06:06:24 PM CET 
//


package abstractbeans;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the abstractbeans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: abstractbeans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AbstractFinalStep }
     * 
     */
    public AbstractFinalStep createAbstractFinalStep() {
        return new AbstractFinalStep();
    }

    /**
     * Create an instance of {@link AbstractStep }
     * 
     */
    public AbstractStep createAbstractStep() {
        return new AbstractStep();
    }

    /**
     * Create an instance of {@link AbstractUser }
     * 
     */
    public AbstractUser createAbstractUser() {
        return new AbstractUser();
    }

    /**
     * Create an instance of {@link AbstractStartStep }
     * 
     */
    public AbstractStartStep createAbstractStartStep() {
        return new AbstractStartStep();
    }

    /**
     * Create an instance of {@link AbstractAction }
     * 
     */
    public AbstractAction createAbstractAction() {
        return new AbstractAction();
    }

    /**
     * Create an instance of {@link AbstractWorkflow }
     * 
     */
    public AbstractWorkflow createAbstractWorkflow() {
        return new AbstractWorkflow();
    }

    /**
     * Create an instance of {@link AbstractItem }
     * 
     */
    public AbstractItem createAbstractItem() {
        return new AbstractItem();
    }

    /**
     * Create an instance of {@link AbstractMetaEntry }
     * 
     */
    public AbstractMetaEntry createAbstractMetaEntry() {
        return new AbstractMetaEntry();
    }

}
